---
# tasks file for nginx
- name: Install NGinx
  apt: name=nginx state=latest

- name: Copy NGinx config file
  template:
    src: "{{ conf_file }}"
    dest: "{{ nginx_site }}/{{ conf_file }}"

- name: Creating Link
  file:
    src: "{{ nginx_site }}/{{ conf_file }}"
    dest: "{{ nginx_conf }}/{{ conf_file }}"
    state: link

- name: copy the content of the web site
  copy:
    src: templates/index.html
    dest: "{{ html_path }}"

- name: Restart NGinx
  service:
    name: nginx
    state: restarted

# Generating Self-Signed Certificate

- file:
    path: "{{ sslpath }}"
    state: directory

- name: "Generate the private key file to sign the CSR"
  openssl_privatekey:
    path: "{{ pempath }}"
    passphrase: "{{ private_key_password }}"
    cipher: auto

- name: "Generate the CSR file signed with the private key"
  openssl_csr:
    path: "{{ csrpath }}"
    privatekey_path: "{{ pempath }}"
    privatekey_passphrase: "{{ private_key_password }}"
    common_name: "{{ dnsname }}"

- name: "Sign the CSR file as a CA to turn it into a certificate"
  openssl_certificate:
    path: "{{ crtpath }}"
    privatekey_path: "{{ pempath }}"
    privatekey_passphrase: "{{ private_key_password }}"
    csr_path: "{{ csrpath }}"
    provider: selfsigned

- name: "Convert the signed certificate into a PKCS12 file with the attached private key"
  openssl_pkcs12:
    action: export
    path: "{{ pfxpath }}"
    name: "{{ dnsname }}"
    privatekey_path: "{{ pempath }}"
    privatekey_passphrase: "{{ private_key_password }}"
    passphrase: password
    certificate_path: "{{ crtpath }}"
    state: present
